// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinUITest.Data;

#nullable disable

namespace WinUITest.DataProvider.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20220513110233_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("WinUITest.Data.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Balance = 25.98m,
                            CustomerCode = "A001",
                            Name = "Acorn Antiques"
                        },
                        new
                        {
                            CustomerId = 2,
                            Balance = 0.00m,
                            CustomerCode = "M123",
                            Name = "Milliways Restaurants Ltd"
                        },
                        new
                        {
                            CustomerId = 3,
                            Balance = -25.00m,
                            CustomerCode = "T014",
                            Name = "Trotters Independent Traders"
                        },
                        new
                        {
                            CustomerId = 4,
                            Balance = 0.00m,
                            CustomerCode = "S001",
                            Name = "Sunshine Desserts Ltd"
                        },
                        new
                        {
                            CustomerId = 5,
                            Balance = 0.00m,
                            CustomerCode = "P145",
                            Name = "Bob's Burger Restaurants Ltd"
                        });
                });

            modelBuilder.Entity("WinUITest.Data.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Price = 12.99m,
                            ProductCode = "EGG48",
                            ProductName = "48 Class A Eggs"
                        },
                        new
                        {
                            ProductId = 2,
                            Price = 8.50m,
                            ProductCode = "MILK25L",
                            ProductName = "25L Full Fat Milk"
                        },
                        new
                        {
                            ProductId = 3,
                            Price = 7.15m,
                            ProductCode = "SUGAR2KG",
                            ProductName = "2KG White Sugar"
                        },
                        new
                        {
                            ProductId = 4,
                            Price = 22.19m,
                            ProductCode = "VAN001",
                            ProductName = "500ml Vanilla Essence"
                        });
                });

            modelBuilder.Entity("WinUITest.Data.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2022, 5, 13, 12, 2, 32, 967, DateTimeKind.Local).AddTicks(751));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            CustomerId = 1,
                            TransactionDate = new DateTime(2021, 12, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Type = "I",
                            Value = 48.17m
                        },
                        new
                        {
                            TransactionId = 2,
                            CustomerId = 1,
                            TransactionDate = new DateTime(2021, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Type = "C",
                            Value = -22.19m
                        },
                        new
                        {
                            TransactionId = 3,
                            CustomerId = 3,
                            TransactionDate = new DateTime(2021, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Type = "C",
                            Value = -14.30m
                        });
                });

            modelBuilder.Entity("WinUITest.Data.TransactionDetail", b =>
                {
                    b.Property<int>("TransactionDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionDetailId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionDetails");

                    b.HasData(
                        new
                        {
                            TransactionDetailId = 1,
                            ProductCode = "EGG48",
                            Quantity = 2,
                            TransactionId = 1,
                            Value = 25.98m
                        },
                        new
                        {
                            TransactionDetailId = 2,
                            ProductCode = "VAN001",
                            Quantity = 1,
                            TransactionId = 1,
                            Value = 22.19m
                        },
                        new
                        {
                            TransactionDetailId = 3,
                            ProductCode = "VAN001",
                            Quantity = 1,
                            TransactionId = 2,
                            Value = -22.19m
                        },
                        new
                        {
                            TransactionDetailId = 4,
                            ProductCode = "SUGAR2KG",
                            Quantity = 2,
                            TransactionId = 3,
                            Value = -14.30m
                        });
                });

            modelBuilder.Entity("WinUITest.Data.Transaction", b =>
                {
                    b.HasOne("WinUITest.Data.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WinUITest.Data.TransactionDetail", b =>
                {
                    b.HasOne("WinUITest.Data.Transaction", "Transaction")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("WinUITest.Data.Customer", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("WinUITest.Data.Transaction", b =>
                {
                    b.Navigation("TransactionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
